#![allow(clippy::unwrap_used)]

use crate::operation::CreateProjectOutput;
use runtime_core::{FlowOperation, RuntimeResult, cancel::CancelableSender, channel::Sender};
use runtime_doc::operations::project_extension_setup::ProjectExtensionSetupOutput;
use std::fs;

use super::{
    CollectCreateSender, CollectExtSender, ProjectSetupInput, ProjectSetupOp, ProjectSetupOutput,
};

struct MockSender {
    output: Option<ProjectSetupOutput>,
}

impl MockSender {
    fn new() -> Self {
        Self { output: None }
    }
}

impl Sender<ProjectSetupOutput> for MockSender {
    async fn send(&mut self, value: ProjectSetupOutput) -> RuntimeResult<()> {
        self.output = Some(value);
        Ok(())
    }
}

impl CancelableSender<ProjectSetupOutput> for MockSender {
    fn is_cancelled(&self) -> bool {
        false
    }
}

fn write_documentation_template(root: &std::path::Path) {
    let template_dir = root.join("doc").join("template").join("ai");
    fs::create_dir_all(&template_dir).unwrap();

    let template_content = "---
id: ai-rule-00003-documentation
title: Documentation Rule
created: <YYYY-MM-DD>
updated: <YYYY-MM-DD>
---

# Supported Types

#{types}
";
    fs::write(template_dir.join("template-00006-documentation.md"), template_content).unwrap();
}

#[tokio::test]
async fn test_project_setup_op_runs_composed_chain() {
    let now =
        std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos();
    let temp_dir = std::env::temp_dir().join(format!("vector_setup_test_{now}"));
    fs::create_dir_all(&temp_dir).unwrap();

    write_documentation_template(&temp_dir);

    let target_dir = runtime_io::path::IoPath::new(&temp_dir);

    let input = ProjectSetupInput {
        target_dir: target_dir.clone(),
        project_name: "setup_test_project".to_string(),
        force: false,
    };

    let mut sender = MockSender::new();
    ProjectSetupOp.run(input, &mut sender).await.unwrap();

    let output = sender.output.unwrap();

    assert!(
        output.project.message.contains("setup_test_project"),
        "project creation output must name the project"
    );

    let rule_path = output.extension.documentation_rule_path.as_path();
    assert!(rule_path.exists(), "documentation rule must be generated by the composed chain");

    let content = fs::read_to_string(rule_path).unwrap();
    assert!(
        !content.contains("#{types}"),
        "type placeholder must be replaced in documentation rule"
    );

    fs::remove_dir_all(&temp_dir).unwrap();
}

#[tokio::test]
async fn test_project_setup_op_bootstrap_files_are_provisioned() {
    let now =
        std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos();
    let temp_dir = std::env::temp_dir().join(format!("vector_setup_provision_{now}"));
    fs::create_dir_all(&temp_dir).unwrap();

    write_documentation_template(&temp_dir);

    let target_dir = runtime_io::path::IoPath::new(&temp_dir);

    let input =
        ProjectSetupInput { target_dir, project_name: "provision_test".to_string(), force: false };

    let mut sender = MockSender::new();
    ProjectSetupOp.run(input, &mut sender).await.unwrap();

    assert!(
        temp_dir.join("CLAUDE.md").exists(),
        "CLAUDE.md must be provisioned by CreateProjectOp"
    );
    assert!(
        temp_dir.join(".vector/document-types.yaml").exists(),
        "document-types.yaml must be provisioned by CreateProjectOp"
    );
    assert!(
        temp_dir.join(".vector/agents.yaml").exists(),
        "agents.yaml must be provisioned by CreateProjectOp"
    );
    assert!(
        temp_dir.join(".vector/language-rules.yaml").exists(),
        "language-rules.yaml must be provisioned by CreateProjectOp"
    );
    assert!(
        temp_dir.join(".claude/settings.local.json").exists(),
        "settings.local.json must be provisioned by CreateProjectOp"
    );

    fs::remove_dir_all(&temp_dir).unwrap();
}

#[tokio::test]
async fn collect_create_sender_stores_output() {
    let mut captured = None;
    let mut sender = CollectCreateSender { inner: &mut captured };

    sender
        .send(CreateProjectOutput { message: "created".to_string(), skipped_files: Vec::new() })
        .await
        .unwrap();

    assert_eq!(captured.unwrap().message, "created");
}

#[tokio::test]
async fn collect_ext_sender_stores_output() {
    let (_temp_dir, root) = tempfile::tempdir()
        .map(|dir| {
            let root = runtime_io::path::IoPath::new(dir.path());
            write_documentation_template(dir.path());
            (dir, root)
        })
        .unwrap();
    let input = ProjectSetupInput {
        target_dir: root,
        project_name: "collector-test".to_string(),
        force: false,
    };

    let mut outer_sender = MockSender::new();
    ProjectSetupOp.run(input, &mut outer_sender).await.unwrap();
    let extension_output = outer_sender.output.unwrap().extension;

    let mut captured = None;
    let mut sender = CollectExtSender { inner: &mut captured };
    sender.send(extension_output).await.unwrap();

    let output: ProjectExtensionSetupOutput = captured.unwrap();
    assert!(
        output.documentation_rule_path.as_path().ends_with("ai-rule-00003-documentation.md"),
        "collector must retain the extension output path"
    );
}

#[test]
fn collect_senders_are_never_cancelled() {
    let mut create_output = None;
    let create_sender = CollectCreateSender { inner: &mut create_output };
    assert!(!create_sender.is_cancelled(), "create collector must never report cancellation");

    let mut ext_output = None;
    let ext_sender = CollectExtSender { inner: &mut ext_output };
    assert!(!ext_sender.is_cancelled(), "extension collector must never report cancellation");
}
